java -cp out\production\logarlec proto.Main test 1
java -cp out\production\logarlec proto.Main test 2
java -cp out\production\logarlec proto.Main test 3
java -cp out\production\logarlec proto.Main test 4
java -cp out\production\logarlec proto.Main test 5
java -cp out\production\logarlec proto.Main test 6
java -cp out\production\logarlec proto.Main test 7
java -cp out\production\logarlec proto.Main test 8
java -cp out\production\logarlec proto.Main test 9
java -cp out\production\logarlec proto.Main test 10
java -cp out\production\logarlec proto.Main test 11
java -cp out\production\logarlec proto.Main test 12
java -cp out\production\logarlec proto.Main test 13
java -cp out\production\logarlec proto.Main test 14
java -cp out\production\logarlec proto.Main test 15
java -cp out\production\logarlec proto.Main test 16
java -cp out\production\logarlec proto.Main test 17
java -cp out\production\logarlec proto.Main test 18
java -cp out\production\logarlec proto.Main test 19
java -cp out\production\logarlec proto.Main test 20
java -cp out\production\logarlec proto.Main test 21
java -cp out\production\logarlec proto.Main test 22
java -cp out\production\logarlec proto.Main test 23
java -cp out\production\logarlec proto.Main test 24
java -cp out\production\logarlec proto.Main test 25
java -cp out\production\logarlec proto.Main test 26
java -cp out\production\logarlec proto.Main test 27
java -cp out\production\logarlec proto.Main test 28
java -cp out\production\logarlec proto.Main test 29
java -cp out\production\logarlec proto.Main test 30